name: Check DefectDojo Connectivity

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: [self-hosted, defectdojo]

    steps:
      - name: Probar conexión a DefectDojo
        run: |
          echo "Probando conexión a http://10.0.0.4:8080..."
          curl -I http://10.0.0.4:8080 || echo "❌ No se pudo conectar"
